config/routes.rb
JennyAjax::Application.routes.draw do
  root :to => 'menus#index'
  resources :menus, :only => [:index, :create, :show] do
    resources :items, :only => [:create]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :menu
  attr_accessible :name, :price
  validates :name, :presence => true, :uniqueness =>true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true, :uniqueness =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menus = Menu.all
    @menu = Menu.new
  end

  def create
    @menu = Menu.new params[:menu]

    if @menu.save
      render :json => { :menu_template => render_to_string(:partial => 'menu', :locals => {:menu => @menu}) }
    else
      render :json => {:error => @menu.errors.full_messages.join(", ")}, :status => :unprocessable_entity
    end
  end

  def show
    @menu = Menu.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome Menus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div id="main-title"><%= link_to "Awesome Menus", root_path %></div>
    <%= yield %>
  </div>
</body>
</html>

app/views/menus/_menu.html.erb
<li class="list-group-item"><%= menu.name %> <%= link_to "details", menu_path(menu), :class => "details-view"  %></li>

<%= render 'menudetail', :menu => menu %>

app/views/menus/_menudetail.html.erb
<div class = "detail-form">
  <%=menu.name %>
</div>

app/views/menus/index.html.erb
<%= link_to "New Menu", "#", :class => 'new-menu' %>


<%= form_for @menu, :remote => true, :html => {:class => 'hidden'} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Add Menu" %>
<% end %>


<h2>Menus</h2>
<div class="menu-list">

  <ul class="menus list-group">
    <% @menus.each do |menu| %>
      <%= render 'menu', :menu => menu %>
    <% end %>
  </ul>
</div>

app/views/menus/show.html.erb
<%= @menu.name %>